### ISSUE TITLE
Search with chineese charaters doesn't work as expected on iphone

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/cordova-app#10]
When doing a search on the Iphone app with chineese charaters, the results show all products.
Here is a screenshot
![chineese_search_iphone](https://cloud.githubusercontent.com/assets/43065/6412223/fffd9284-be78-11e4-97c2-7c985d140df2.png)

**Comment by sl956** [comment]
This is a direct consequence of this issue:

**Comment by kyzh** [comment]
Since the product opener bug has been fixed, this shoud now be ok
