### ISSUE TITLE
Provide an .apk

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/cordova-app#2]
We should provide an apk for people without google play

**Comment by kyzh** [comment]
done world.openfoodfacts.org/files/off.apk

**Comment by liotier** [comment]
Thank you for providing the APK !

On Cyanogenmod 11-20141112-SNAPSHOT-M12-jflte (Android 4.4.4) on a GT-I90505, the installation fails with "App not installed".

Are there any dependencies that users should be aware of ?

**Comment by teolemon** [comment]
We use the Moodstock scanner for augmented reality for Nutrition Codes.
